name: aquarium
description: "A new Flutter project."

publish_to: 'none' 



environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  routefly: ^1.0.9
  asp: ^1.3.0
  auto_injector: ^2.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.9
  cloud_firestore: ^4.15.8  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

